// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqegfevdzvnxsajrotrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZWdmZXZkenZueHNhanJvdHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NzQzNTksImV4cCI6MjA1NjQ1MDM1OX0.7ee-cZFd3f0CJZNOMw1WF28gbLQDnc_0r_mfxgIAKcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);